### ISSUE TITLE
Oauth?

### ISSUE THREAD

**Issue by attackant** [redcap3000/meteor-wordpress-json-api#2]
Does this project have any WP authentication options? I've been looking for a simple way to allow single signon between WP and Meteor...

**Comment by redcap3000** [comment]
None that this moment. If I were going to implement this I would make another package that connects directly to wordpress like wordscript ( http://github.com/redcap3000/Wordscript )  does - so you could open your mysql database to external connections , or run the meteor installation on a server to complete this. Actually theres a node js client in that repo but I haven't gotten around to porting it to meteor...

**Comment by attackant** [comment]
Cool thank you.
